title: Yakshaver.org
description: > # this means to ignore newlines until "baseurl:"
  Personal web site for links to open source Bitcoin work.
# social links
author: "Richard Myers"
email: remyers@yakshaver.org

theme: minima

twitter_username: remyers_
github_username:  remyers

show_excerpts: true # set to false to remove excerpts on the homepage

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - bitcoin/index.md
  - mesh/index.md
  - about.md

include: [".well-known"]
